export const TOGGLE_TURN_TIMER = 'TOGGLE_TURN_TIMER';
export const TOGGLE_QUICK_GAME = 'TOGGLE_QUICK_GAME';
export const SELECT_WORD_GROUP = 'SELECT_WORD_GROUP';
export const ADD_CUSTOM_WORD = 'ADD_CUSTOM_WORD';
export const DELETE_CUSTOM_WORD = 'DELETE_CUSTOM_WORD';
export const SET_GAME_SETTINGS = 'SET_GAME_SETTINGS';
export const RESET_STATE = 'RESET_STATE';
export const SET_LINK = 'SET_LINK';
