export const TOGGLE_TURN_TIMER = 'TOGGLE_TURN_TIMER';
export const TOGGLE_QUICK_GAME = 'TOGGLE_QUICK_GAME';
export const SELECT_WORD_GROUP = 'SELECT_WORD_GROUP';
export const UPDATE_CUSTOM_WORDS = 'UPDATE_CUSTOM_WORDS';
export const RESET_STATE = 'RESET_STATE';
